### ISSUE TITLE
Blockerbot scheduled task does not run successfully in Production

### ISSUE THREAD

**Issue by prehnRA** [revelrylabs/slax#92]
## Background

We have implemented the Blockerbot command as both a slash command and a scheduled task in Slax. The command works in testing when run manually, but has not been running successfully on the schedule. We need to resolve this.

Here's an excerpt from the logs that may help explain what is happening:

```
2019-06-06T14:25:00+00:00 slax[cmd.v46.zt79r]: ** (FunctionClauseError) no function clause matching in Access.get/3
2019-06-06T14:25:00+00:00 slax[cmd.v46.zt79r]:     (elixir) lib/access.ex:320: Access.get({"documentation_url", "https://developer.github.com/v3"}, "number", nil)
2019-06-06T14:25:00+00:00 slax[cmd.v46.zt79r]:     (elixir) lib/enum.ex:1331: anonymous fn/3 in Enum.map/2
2019-06-06T14:25:00+00:00 slax[cmd.v46.zt79r]:     (stdlib) maps.erl:257: :maps.fold_1/3
2019-06-06T14:25:00+00:00 slax[cmd.v46.zt79r]:     (elixir) lib/enum.ex:1956: Enum.map/2
2019-06-06T14:25:00+00:00 slax[cmd.v46.zt79r]:     (slax) lib/slax/event_sink.ex:17: Slax.EventSink.fetch_issues_events/2
2019-06-06T14:25:00+00:00 slax[cmd.v46.zt79r]:     (slax) lib/slax/commands/latency.ex:19: Slax.Commands.Latency.text_for_org_and_repo/3
2019-06-06T14:25:00+00:00 slax[cmd.v46.zt79r]:     (slax) lib/slax/scheduler.ex:22: Slax.Scheduler.send_repo_to_channel/3
2019-06-06T14:25:00+00:00 slax[cmd.v46.zt79r]:     (elixir) lib/enum.ex:769: Enum."-each/2-lists^foreach/1-0-"/2
2019-06-06T14:25:00+00:00 slax[cmd.v46.zt79r]: Function: #Function<7.52749505/0 in Quantum.Executor.run/4>
2019-06-06T14:25:00+00:00 slax[cmd.v46.zt79r]:     Args: []
```

## Scenario

- WHEN it is 9:25am
- [ ] THEN any channels with Blockerbot enabled should receive an update

**Comment by jpatricknola** [comment]
i didnt have enough time to get set up but from looking at it I have some initial questions.   With the knowledge that the scheduler works correctly in the local environment and not on production, I'm looking at two files in particular 

1) config.exs
2) prod_runtime_config.exs

I'm wondering if the runtime file needs the equivalent of this from the config file, or if there is something not happening as expected with import_config

<img width="753" alt="Screen Shot 2019-07-02 at 1 53 27 PM" src="https://user-images.githubusercontent.com/6878242/60539213-c349c380-9cd1-11e9-9799-85703792c00d.png">

**Comment by grossvogel** [comment]
I got a bit curious so I thought I'd drive by to offer what little insight I have. The error definitely seems to be triggered on [this line](https://github.com/revelrylabs/slax/blob/master/lib/slax/event_sink.ex#L17) and it looks `{"documentation_url", "https://developer.github.com/v3"}` is one of the items in `issues`, and that doesn't look like an _issue_ to me.

Perhaps we have a single issue instead of the expected list of issues?
Or perhaps we have something else entirely that this function wasn't expecting?

**Comment by jwietelmann** [comment]
> Perhaps we have a single issue instead of the expected list of issues?

This is what I would investigate first. It makes the most sense with the symptoms.

**Comment by jwietelmann** [comment]
Actually, I think what's happening is there's an unhandled API error of some kind that we're eating. https://github.com/revelrylabs/slax/blob/master/lib/slax/github.ex#L162

**Comment by jwietelmann** [comment]
After a long pairing session with @fireside68 ...

## Complete analysis

* The `GITHUB_API_TOKEN`, an env var whose value should be set to a GitHub "Personal Access Token" (ideally of a readonly machine user), was never set.
* The code for extracting that value from the app's configuration was never correct.
* The API was returning an error response.
* We were eating the error and silently returning the response body to a caller that was expecting a list of issues.
* The caller had no guards to guarantee it was working with a list.
* The caller function would then enumerate the key/value pairs of the error response.
* Eventually it would raise a full-on runtime error when it reached code that depended on there being an issue map instead of a key/value tuple.

## Solution

* Generate a personal access token for the `revelry-machine-readonly` user, and set `GITHUB_API_TOKEN` to that value in deis: Done.
* Fix the configuration fetching code: #106 
* Add a guard to make sure the function that is supposed to operate on a list of issue maps has indeed received a list, so errors are raised earlier and more clearly: #106
